## Numpy array and basics
learn about numpy with  chai aur code

In [2]:
import numpy as np

### creating array from list

In [6]:
arr_0d=np.array(84)
print("0D Array",arr_0d)
print(type(arr_0d))

arr_1d=np.array([1,2,3,4,5])
print("1D Array",arr_1d)
print(type(arr_1d))

arr_2d=np.array([[1,2,3],[1,3,4]])
print("2D Array",arr_2d)
print(type(arr_2d))

0D Array 84
<class 'numpy.ndarray'>
1D Array [1 2 3 4 5]
<class 'numpy.ndarray'>
2D Array [[1 2 3]
 [1 3 4]]
<class 'numpy.ndarray'>


### List vs numpy array

In [ ]:
py_list=[43,5.3,5,22,"abcd","example"]
print("Python List multiplication :",py_list*2)
print(type(py_list))

Python List multiplication : [43, 5.3, 5, 22, 'abcd', 'example', 43, 5.3, 5, 22, 'abcd', 'example']
<class 'list'>


In [11]:
npArray=np.array([3,5,3]) #element wise multipllication
print("Python Array multiplication :",npArray*2)

Python Array multiplication : [ 6 10  6]


In [13]:
import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time",time.time()-start)


start1=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy operation time",time.time()-start1)


 List operation time 0.23538994789123535

 Numpy operation time 0.006273984909057617


### Creating array from scratch

In [2]:
Zero=np.zeros((3,4))
print("zeros array:\n",Zero)

one=np.ones((3,4))
print("One array:\n",one)

full=np.full((4,5),7)
print("Full array:\n",full)

random=np.random.random((3,4))
print("Random array:\n",random)

sequence=np.arange(0,10,2)
print("Sequence array:\n",sequence)


zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array:
 [[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
Random array:
 [[0.0551732  0.92216432 0.78459818 0.31791169]
 [0.28850054 0.412603   0.24007131 0.60769033]
 [0.83209656 0.35483125 0.98223428 0.04832933]]
Sequence array:
 [0 2 4 6 8]


### Vector Matrix and Tensor

In [9]:
vector=np.array([7,4,6,1,9,6,8,0,1,5])
print("Vector ",vector)

matrix=np.array([[74,61,96,80,15],
                 [97,98,80,78,67]])
print("Matrix",matrix)

tensor=np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[1,2,3]]])
print("Tensor",tensor)


Vector  [7 4 6 1 9 6 8 0 1 5]
Matrix [[74 61 96 80 15]
 [97 98 80 78 67]]
Tensor [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


### Array  properties

In [14]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("Size",arr.size)
print("Dtype",arr.dtype)


Shape (2, 3)
Dimension 2
Size 6
Dtype int64


### Array Reshaping

In [21]:
arr=np.arange(12)
print("Original Array ",arr)

reshaped=arr.reshape((3,4))
print("\n Reshaped Array ",reshaped)

flattened=reshaped.flatten()
print("\n Flatten Array",flattened)


# ravel (returns view , instead of copy)
raveled=reshaped.ravel()
print("\n Ravel Array",raveled)

#Transpose
transpose=reshaped.T
print("\n Transpose Array",transpose)


Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flatten Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Ravel Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose Array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
